In [9]:
import time
from datetime import datetime
import numpy as np
import pandas as pd

In [24]:
arr1 = np.random.rand(950)
arr2 = np.random.rand(950)
arr3 = np.random.rand(950)

dataOut = np.array([arr1, arr2, arr3])

newDataDf = pd.DataFrame(dataOut).transpose()

In [25]:
newDataDf

            0         1         2
0    0.740162  0.100132  0.486998
1    0.233447  0.527865  0.073211
2    0.789583  0.555252  0.362197
3    0.440702  0.101852  0.438041
4    0.111778  0.048657  0.981911
..        ...       ...       ...
945  0.328991  0.360232  0.518772
946  0.616562  0.852724  0.632295
947  0.211765  0.960460  0.469267
948  0.304453  0.259790  0.595976
949  0.971829  0.194941  0.720364

[950 rows x 3 columns]

In [18]:
dataLabel = time.time_ns()/1e9
print(dataLabel)

1732701409.143654

In [20]:
start = pd.Timestamp(dataLabel, unit="s")
start

Timestamp('2024-11-27 09:56:49.143654108')

In [26]:
dataLen = newDataDf.shape[0]
dataLen

950

In [27]:
samplingRate = 10000
end = start + pd.Timedelta(dataLen*1/samplingRate, unit="seconds")

In [28]:
end

Timestamp('2024-11-27 09:56:49.238654108')

In [30]:
end  - start

Timedelta('0 days 00:00:00.095000')

In [31]:
timeIndex = pd.date_range(start=start, end=end, periods=dataLen)

In [33]:
timeIndex[-1] - timeIndex[0]

Timedelta('0 days 00:00:00.095000')

In [34]:
newDataDf.index = pd.DatetimeIndex(timeIndex)

In [35]:
newDataDf

                                      0         1         2
2024-11-27 09:56:49.143654108  0.740162  0.100132  0.486998
2024-11-27 09:56:49.143754213  0.233447  0.527865  0.073211
2024-11-27 09:56:49.143854318  0.789583  0.555252  0.362197
2024-11-27 09:56:49.143954424  0.440702  0.101852  0.438041
2024-11-27 09:56:49.144054529  0.111778  0.048657  0.981911
...                                 ...       ...       ...
2024-11-27 09:56:49.238253686  0.328991  0.360232  0.518772
2024-11-27 09:56:49.238353791  0.616562  0.852724  0.632295
2024-11-27 09:56:49.238453897  0.211765  0.960460  0.469267
2024-11-27 09:56:49.238554002  0.304453  0.259790  0.595976
2024-11-27 09:56:49.238654108  0.971829  0.194941  0.720364

[950 rows x 3 columns]